usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

pagina_estatica:
    path: /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }
    
_pagina_estatica:
    path: /sitio/{pagina}/
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: pagina_estatica }
    
_portada:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%' }
    
portada:
    path: /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada }

detalle_oferta:
    path: /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }
    requirements:
        slug: .+

ciudad_cambiar:
    path: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }
    requirements:
        ciudad: .+
        
ciudad_recientes:
    path: /{ciudad}/recientes
    defaults: { _controller: CiudadBundle:Default:recientes }
    
tienda_portada:
    path: /{ciudad}/tiendas/{tienda}
    defaults: { _controller: TiendaBundle:Default:portada }
